import React from 'react'
import Gallery from './Gallery';

function Tourism() {
  return (
    <>
    <Gallery title="Taj Mahal" location='http://www.jdoqocy.com/click-2339553-10842362?URL=http%3A%2F%2Fwww.tripadvisor.com%2FSmartDeals-g297683-Agra_Agra_District_Uttar_Pradesh-Hotel-Deals.html%3Fcja%3D10842362%26cjp%3D2339553%26m%3D13092' image='https://www.planetware.com/photos-large/IND/india-top-attractions-taj-mahal.jpg'  name='Taj' desc="Perhaps India 's most recognizable building, the Taj Mahal is also the world's most famous testimony to the power of love. Named after Mumtaz Mahal, the favorite wife of Emperor Shah Jahan, this most beautiful of mausoleums was begun upon her death in 1631 and took 20,000 workmen until 1648 to complete.The best time to visit is either at dawn or dusk when the atmosphere is brilliantly altered by the change in lighting. If possible, try to catch a view of the Taj Mahal's reflection from the far bank of the Yamuna River-it makes for a memorable (and safe) selfie."/>
    <Gallery title="Holy Varansi" location='http://www.jdoqocy.com/click-2339553-10842362?URL=http%3A%2F%2Fwww.tripadvisor.com%2FSmartDeals-g297685-Varanasi_Varanasi_District_Uttar_Pradesh-Hotel-Deals.html%3Fcja%3D10842362%26cjp%3D2339553%26m%3D13092' image='https://www.planetware.com/photos-large/IND/india-top-attractions-varanasi.jpg'  name='Shiva' desc="Dating back to the 8th century BC, Varanasi is one of the oldest still inhabited cities in the world. A major pilgrimage center for Hindus, this holy city has long been associated with the mighty Ganges River, one of the faith's most important religious symbols.Varanasi offers many reasons to visit, not least of them the chance to explore the Old Quarter adjacent to the Ganges where you'll find the Kashi Vishwanath Temple, built in 1780. The New Vishwanath Temple with its seven separate temples is also of interest."/>
    <Gallery title="Red Fort" location='http://www.jdoqocy.com/click-2339553-10842362?URL=http%3A%2F%2Fwww.tripadvisor.com%2FSmartDeals-g297685-Varanasi_Varanasi_District_Uttar_Pradesh-Hotel-Deals.html%3Fcja%3D10842362%26cjp%3D2339553%26m%3D13092'image='https://www.planetware.com/photos-large/IND/india-top-attractions-red-fort.jpg'  name='Red' desc="Built by Shah Jahan in 1648 as the seat of Mughal power – a role it maintained until 1857 – the magnificent crescent-shaped Red Fort in New Delhi, named after the stunning red sandstone used in its construction, covers a vast area of more than two square kilometers, all of it surrounded by a large moat.Highlights include its two largest gates: the impressive Lahore Gate (the fort's main entrance) and the elaborately decorated Delhi Gate, once used by the emperor for ceremonial processions.A fun part of a visit is exploring Chatta Chowk, a 17th-century covered bazaar selling everything from jewelry to silk garments, as well as souvenirs and food items. While you can explore the fort yourself"/>
    <Gallery title="Goa beaches" location='http://www.jdoqocy.com/click-2339553-10842362?URL=http%3A%2F%2Fwww.tripadvisor.com%2FSmartDeals-g297683-Agra_Agra_District_Uttar_Pradesh-Hotel-Deals.html%3Fcja%3D10842362%26cjp%3D2339553%26m%3D13092' image='https://www.planetware.com/wpimages/2019/08/india-top-attractions-goa-beaches.jpg'  name='goa' desc="Long known within India as the 'go-to' destination for those seeking a great beach holiday, Goa's beautiful western coastline, overlooking the Arabian Sea, has only recently been discovered by tourists from overseas. Goa's more than 60 miles of coastline is home to some of the world's loveliest beaches, each with their own particular appeal.Also worth a visit is Divar Island, accessed by ferry from Old Goa. Highlights include Piedade, a typical Goan village and home to the Church of Our Lady of Compassion with its interesting stucco work, Baroque plaster decorations, and altars, as well as stunning views of the surrounding countryside."/>
    <Gallery title="Wild life sanctuary" location='http://www.jdoqocy.com/click-2339553-10842362?URL=http%3A%2F%2Fwww.tripadvisor.com%2FSmartDeals-g297683-Agra_Agra_District_Uttar_Pradesh-Hotel-Deals.html%3Fcja%3D10842362%26cjp%3D2339553%26m%3D13092' image='https://www.planetware.com/photos-large/IND/india-top-attractions-periyar-national-park-wildlife-sanctuary.jpg'  name='Taj' desc="One of South India's most popular tourist attractions, Periyar National Park and Wildlife Sanctuary is centered around a lake built by British engineers in 1895 for irrigation and to provide water to the city of Madurai.Established in 1934, this beautiful park is home to numerous species of mammals, including a large free-roaming Indian elephant population, wild boar, otters, the lion-tailed macaque, and more than 20 Bengal tigers. Bird-watching is a popular activity with frequent sightings of species such as darters, storks, kingfishers, hornbills, and racket-tailed drongos, along with many interesting varieties of butterflies."/>
    </>
  )
}

export default Tourism